"""Add shift operator and standard time

Revision ID: 205a70514992
Revises: 86621fdbcbb5
Create Date: 2026-01-18 23:44:57.263083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205a70514992'
down_revision: Union[str, Sequence[str], None] = '86621fdbcbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycle_time_records', sa.Column('shift', sa.String(), nullable=True))
    op.add_column('cycle_time_records', sa.Column('operator', sa.String(), nullable=True))
    op.add_column('work_elements', sa.Column('standard_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_elements', 'standard_time')
    op.drop_column('cycle_time_records', 'operator')
    op.drop_column('cycle_time_records', 'shift')
    # ### end Alembic commands ###
