"""Initial migration for production tables

Revision ID: 86621fdbcbb5
Revises: 
Create Date: 2025-10-18 03:33:57.370491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86621fdbcbb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_code', sa.String(), nullable=False),
    sa.Column('station_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_index(op.f('ix_stations_station_code'), 'stations', ['station_code'], unique=True)
    op.create_table('work_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('element_code', sa.String(), nullable=False),
    sa.Column('element_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_elements_element_code'), 'work_elements', ['element_code'], unique=False)
    op.create_index(op.f('ix_work_elements_id'), 'work_elements', ['id'], unique=False)
    op.create_table('cycle_time_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('work_element_id', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=True),
    sa.Column('cycle_time', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_only', sa.String(), nullable=True),
    sa.Column('is_outlier', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['work_element_id'], ['work_elements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_time_records_date_only'), 'cycle_time_records', ['date_only'], unique=False)
    op.create_index(op.f('ix_cycle_time_records_id'), 'cycle_time_records', ['id'], unique=False)
    op.create_table('statistical_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_element_id', sa.Integer(), nullable=False),
    sa.Column('avg_time', sa.Float(), nullable=False),
    sa.Column('stdev_time', sa.Float(), nullable=True),
    sa.Column('variance_time', sa.Float(), nullable=True),
    sa.Column('lower_limit', sa.Float(), nullable=True),
    sa.Column('upper_limit', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['work_element_id'], ['work_elements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistical_thresholds_id'), 'statistical_thresholds', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistical_thresholds_id'), table_name='statistical_thresholds')
    op.drop_table('statistical_thresholds')
    op.drop_index(op.f('ix_cycle_time_records_id'), table_name='cycle_time_records')
    op.drop_index(op.f('ix_cycle_time_records_date_only'), table_name='cycle_time_records')
    op.drop_table('cycle_time_records')
    op.drop_index(op.f('ix_work_elements_id'), table_name='work_elements')
    op.drop_index(op.f('ix_work_elements_element_code'), table_name='work_elements')
    op.drop_table('work_elements')
    op.drop_index(op.f('ix_stations_station_code'), table_name='stations')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
